In [1]:
import pandas as pd

df = pd.read_csv('mock_sales.csv', header='infer')

print(df.shape)
df.head(5)

(36, 5)

   Sale ID   Area   Product  Price  Quantity
0     2001  North  Notebook     38         4
1     2002  North  Notebook     40         6
2     2003  North  Notebook     42         8
3     2004  North       Pen     12         9
4     2005  North       Pen     14        11

In [2]:
#3.1 Create Revenue
df['Revenue'] = df['Price'] * df['Quantity']

df.head(5)

   Sale ID   Area   Product  Price  Quantity  Revenue
0     2001  North  Notebook     38         4      152
1     2002  North  Notebook     40         6      240
2     2003  North  Notebook     42         8      336
3     2004  North       Pen     12         9      108
4     2005  North       Pen     14        11      154

In [3]:
#3.2 Average Price for each Area using groupby()
df.groupby('Area')['Price'].mean()

Area
East     22.333333
North    26.666667
South    26.000000
West     32.000000
Name: Price, dtype: float64

In [4]:
#3.3 Average Price for each Area using pivot_table()
df.pivot_table(values='Price', index='Area', aggfunc='mean')

           Price
Area
East   22.333333
North  26.666667
South  26.000000
West   32.000000

In [5]:
#3.4 Average Price and Quantity for each Area using groupby()
df.groupby('Area')[['Price', 'Quantity']].mean()

           Price   Quantity
Area
East   22.333333  10.777778
North  26.666667   9.444444
South  26.000000  10.888889
West   32.000000  10.666667

In [6]:
#3.5 Average Price and Quantity for each Area using pivot_table()
df.pivot_table(
    values=['Price', 'Quantity'],
    index='Area',
    aggfunc='mean'
)

           Price   Quantity
Area
East   22.333333  10.777778
North  26.666667   9.444444
South  26.000000  10.888889
West   32.000000  10.666667

In [7]:
#3.6 Total Quantity for each Area and Product
df.pivot_table(
    values='Quantity',
    index='Area',
    columns='Product',
    aggfunc='sum',
    fill_value=0
)

Product  Folder  Marker  Notebook  Pen
Area
East         37      24         0   36
North        34       0        18   33
South         0      29        27   42
West         18      33        45    0

In [8]:
#3.7 Total Revenue for each Area and Product
df['Revenue'] = df['Price'] * df['Quantity']

df.pivot_table(
    values='Revenue',
    index='Area',
    columns='Product',
    aggfunc='sum',
    fill_value=0
)

Product  Folder  Marker  Notebook  Pen
Area
East       1016     560         0  584
North       864       0       728  470
South         0     618      1115  638
West        530     800      1943    0